-- Rollback: Convert TIMESTAMP WITH TIME ZONE back to TIMESTAMP
ALTER TABLE tasks 
ALTER COLUMN due_date TYPE TIMESTAMP;

ALTER TABLE tasks
ALTER COLUMN created_at TYPE TIMESTAMP;

ALTER TABLE tasks
ALTER COLUMN completed_at TYPE TIMESTAMP;

ALTER TABLE users
ALTER COLUMN created_at TYPE TIMESTAMP;

ALTER TABLE users
ALTER COLUMN last_active TYPE TIMESTAMP;
